#ifndef BUILDCONSTANTS_H
#define BUILDCONSTANTS_H

//#define INTERPRETER_STEP_MODE
/*
 * *Platform Build Flags, IS_(OSPREFIX)
 */
#define IS_POSIX
#define USE_VERBOSE
#define MAX_LOCALS_SIZE 4096
#define MAX_STACK_SIZE 4096
//#define NEX_USE_TESTBENCH

#endif // BUILDCONSTANTS_H
